/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package persongui;

import java.awt.Component;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author fashaoyou
 */
public class person_Interface extends javax.swing.JFrame {
    
    static DefaultListModel<person> listModel_normal = new DefaultListModel<>();
    static DefaultListModel<UndergradStudent> listModel_underGra = new DefaultListModel<>();
    static DefaultListModel<GraduateStudent> listModel_graduate = new DefaultListModel<>();
    controller pC;
    /**
     * Creates new form person_Interface
     */
    public person_Interface() {
        initComponents();
        
        personList.setModel(listModel_normal);
        underGradList.setModel(listModel_underGra);
        gradList.setModel(listModel_graduate);
        
        pC = new controller(listModel_normal,listModel_underGra,listModel_graduate);
    }

    
    
    void setPanelEnabled(JPanel panel, Boolean isEnabled) {
    panel.setEnabled(isEnabled);
    Component[] components = panel.getComponents();

    for(int i = 0; i < components.length; i++) {
        if(components[i].getClass().getName() == "javax.swing.JPanel") {
            setPanelEnabled((JPanel) components[i], isEnabled);
        }
        components[i].setEnabled(isEnabled);    
    }
    if(panel == personPortion){
        streetAdsField.setEnabled(isEnabled);
    }
    if(panel == graduatePortion){
        titleField.setEnabled(isEnabled);
        areaField.setEnabled(isEnabled);
        streetAdsField_prof.setEnabled(isEnabled);
    }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        personList = new javax.swing.JList<>();
        undergraduatePortion = new javax.swing.JPanel();
        registerYear = new javax.swing.JLabel();
        regisYearField = new javax.swing.JTextField();
        degreeProgram = new javax.swing.JLabel();
        programCombo = new javax.swing.JComboBox<>();
        programYear = new javax.swing.JLabel();
        programYearCombo = new javax.swing.JComboBox<>();
        GPA = new javax.swing.JLabel();
        GPAField = new javax.swing.JTextField();
        credits = new javax.swing.JLabel();
        creditsField = new javax.swing.JTextField();
        graduatePortion = new javax.swing.JPanel();
        scholarship = new javax.swing.JLabel();
        scholarshipField = new javax.swing.JTextField();
        DegreeType = new javax.swing.JLabel();
        degreeCombo = new javax.swing.JComboBox<>();
        thesisPortion = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        titleField = new javax.swing.JTextArea();
        area = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaField = new javax.swing.JTextArea();
        supervisorPortion = new javax.swing.JPanel();
        supervisorTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        personPortion1 = new javax.swing.JPanel();
        name_prof = new javax.swing.JLabel();
        nameField_prof = new javax.swing.JTextField();
        email_prof = new javax.swing.JLabel();
        emailField_prof = new javax.swing.JTextField();
        streetAds_prof = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        streetAdsField_prof = new javax.swing.JTextArea();
        postalCode_prof = new javax.swing.JLabel();
        postalCodeField_prof = new javax.swing.JTextField();
        city_prof = new javax.swing.JLabel();
        cityField_prof = new javax.swing.JTextField();
        prov_prof = new javax.swing.JLabel();
        provCombo_prof = new javax.swing.JComboBox<>();
        phoneWork_prof = new javax.swing.JLabel();
        phoneHome_prof = new javax.swing.JLabel();
        phoneWorkField_prof = new javax.swing.JFormattedTextField();
        phoneHomeField_prof = new javax.swing.JFormattedTextField();
        personPortion = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        streetAds = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        streetAdsField = new javax.swing.JTextArea();
        postalCode = new javax.swing.JLabel();
        postalCodeField = new javax.swing.JTextField();
        city = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        prov = new javax.swing.JLabel();
        provCombo = new javax.swing.JComboBox<>();
        phoneWork = new javax.swing.JLabel();
        phoneHome = new javax.swing.JLabel();
        phoneWorkField = new javax.swing.JFormattedTextField();
        phoneHomeField = new javax.swing.JFormattedTextField();
        buttonPortion = new javax.swing.JPanel();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        loadBtn = new javax.swing.JButton();
        createPersonBtn = new javax.swing.JButton();
        readBtn = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        createUnderBtn = new javax.swing.JButton();
        createGraBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        underGradList = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        gradList = new javax.swing.JList<>();
        errorMsg = new javax.swing.JLabel();
        checkGra = new javax.swing.JCheckBox();
        checkUngrad = new javax.swing.JCheckBox();
        checkPerson = new javax.swing.JCheckBox();
        resetPerson = new javax.swing.JButton();
        resetUngrad = new javax.swing.JButton();
        resetGrad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        personList.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.yellow, null));
        personList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                personListFocusGained(evt);
            }
        });
        personList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(personList);

        undergraduatePortion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        registerYear.setText("Register year");

        degreeProgram.setText("Degree Program");

        programCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arts&Science", "Medicine", "VetMed", "Engineering", "Education", "Business", "Law." }));

        programYear.setText("Year in Program ");

        programYearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        GPA.setText("        GPA");

        credits.setText("Total credits");

        javax.swing.GroupLayout undergraduatePortionLayout = new javax.swing.GroupLayout(undergraduatePortion);
        undergraduatePortion.setLayout(undergraduatePortionLayout);
        undergraduatePortionLayout.setHorizontalGroup(
            undergraduatePortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(undergraduatePortionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(undergraduatePortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, undergraduatePortionLayout.createSequentialGroup()
                        .addGroup(undergraduatePortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(undergraduatePortionLayout.createSequentialGroup()
                                .addComponent(registerYear)
                                .addGap(31, 31, 31)
                                .addComponent(regisYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(undergraduatePortionLayout.createSequentialGroup()
                                .addComponent(programYear)
                                .addGap(18, 18, 18)
                                .addComponent(programYearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59)
                        .addGroup(undergraduatePortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(degreeProgram)
                            .addComponent(GPA, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(undergraduatePortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(undergraduatePortionLayout.createSequentialGroup()
                                .addComponent(GPAField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(undergraduatePortionLayout.createSequentialGroup()
                                .addComponent(programCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 99, Short.MAX_VALUE))))
                    .addGroup(undergraduatePortionLayout.createSequentialGroup()
                        .addComponent(credits)
                        .addGap(33, 33, 33)
                        .addComponent(creditsField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        undergraduatePortionLayout.setVerticalGroup(
            undergraduatePortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(undergraduatePortionLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(undergraduatePortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerYear)
                    .addComponent(regisYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(degreeProgram)
                    .addComponent(programCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(undergraduatePortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(programYear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(programYearCombo)
                    .addComponent(GPA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GPAField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(undergraduatePortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(credits))
                .addGap(30, 30, 30))
        );

        graduatePortion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        scholarship.setText("scholarship");

        DegreeType.setText("DegreeType");

        degreeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masters", "PhD", "MBA", "LawDoc", "MedDoc", "VetmedDoc" }));

        thesisPortion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        title.setText("ThesisTitle");

        titleField.setColumns(20);
        titleField.setRows(5);
        jScrollPane1.setViewportView(titleField);

        area.setText("ThesisArea");

        areaField.setColumns(20);
        areaField.setRows(5);
        jScrollPane4.setViewportView(areaField);

        javax.swing.GroupLayout thesisPortionLayout = new javax.swing.GroupLayout(thesisPortion);
        thesisPortion.setLayout(thesisPortionLayout);
        thesisPortionLayout.setHorizontalGroup(
            thesisPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thesisPortionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thesisPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(thesisPortionLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(thesisPortionLayout.createSequentialGroup()
                        .addComponent(area)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4)))
                .addGap(15, 15, 15))
        );
        thesisPortionLayout.setVerticalGroup(
            thesisPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thesisPortionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(thesisPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(thesisPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(area)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        supervisorPortion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        supervisorTitle.setText("Supervisor_Info");

        personPortion1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        name_prof.setText("Name: ");

        email_prof.setText("Email");

        streetAds_prof.setText("Street  Address: ");

        streetAdsField_prof.setColumns(20);
        streetAdsField_prof.setRows(5);
        jScrollPane8.setViewportView(streetAdsField_prof);

        postalCode_prof.setText("Postal Code: ");

        city_prof.setText("City: ");

        prov_prof.setText("Prov: ");

        provCombo_prof.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BC", "Alberta", "Saskatchewan", "Manitoba", "Ontario", "Quebec", "Newbrunswick", "PEI", "Nova Scotia", "NL", "" }));

        phoneWork_prof.setText("Phone_Work:");

        phoneHome_prof.setText("phone_home:");

        try {
            phoneWorkField_prof.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("306-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            phoneHomeField_prof.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("306-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout personPortion1Layout = new javax.swing.GroupLayout(personPortion1);
        personPortion1.setLayout(personPortion1Layout);
        personPortion1Layout.setHorizontalGroup(
            personPortion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personPortion1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(personPortion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personPortion1Layout.createSequentialGroup()
                        .addComponent(postalCode_prof)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(postalCodeField_prof, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(city_prof, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cityField_prof, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(prov_prof, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(provCombo_prof, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personPortion1Layout.createSequentialGroup()
                        .addComponent(phoneWork_prof)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(phoneWorkField_prof, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneHome_prof)
                        .addGap(18, 18, 18)
                        .addComponent(phoneHomeField_prof, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personPortion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(personPortion1Layout.createSequentialGroup()
                            .addComponent(streetAds_prof)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane8))
                        .addGroup(personPortion1Layout.createSequentialGroup()
                            .addComponent(name_prof, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nameField_prof, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(email_prof, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(emailField_prof, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        personPortion1Layout.setVerticalGroup(
            personPortion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personPortion1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(personPortion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_prof)
                    .addComponent(nameField_prof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_prof, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailField_prof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personPortion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(streetAds_prof)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(personPortion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postalCode_prof, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postalCodeField_prof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city_prof, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityField_prof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prov_prof, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(provCombo_prof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personPortion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneWork_prof)
                    .addComponent(phoneHome_prof)
                    .addComponent(phoneWorkField_prof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneHomeField_prof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout supervisorPortionLayout = new javax.swing.GroupLayout(supervisorPortion);
        supervisorPortion.setLayout(supervisorPortionLayout);
        supervisorPortionLayout.setHorizontalGroup(
            supervisorPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supervisorPortionLayout.createSequentialGroup()
                .addGroup(supervisorPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(supervisorPortionLayout.createSequentialGroup()
                        .addGroup(supervisorPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(supervisorPortionLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(supervisorTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(supervisorPortionLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(supervisorPortionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(personPortion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        supervisorPortionLayout.setVerticalGroup(
            supervisorPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supervisorPortionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(supervisorTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(personPortion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(62, 62, 62)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout graduatePortionLayout = new javax.swing.GroupLayout(graduatePortion);
        graduatePortion.setLayout(graduatePortionLayout);
        graduatePortionLayout.setHorizontalGroup(
            graduatePortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graduatePortionLayout.createSequentialGroup()
                .addGroup(graduatePortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(graduatePortionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(supervisorPortion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(graduatePortionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(thesisPortion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(graduatePortionLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(scholarship)
                        .addGap(18, 18, 18)
                        .addComponent(scholarshipField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(DegreeType)
                        .addGap(18, 18, 18)
                        .addComponent(degreeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        graduatePortionLayout.setVerticalGroup(
            graduatePortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graduatePortionLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(graduatePortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scholarship)
                    .addGroup(graduatePortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(scholarshipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DegreeType)
                        .addComponent(degreeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(supervisorPortion, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(thesisPortion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        personPortion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        name.setText("Name: ");

        email.setText("Email");

        streetAds.setText("Street  Address: ");

        streetAdsField.setColumns(20);
        streetAdsField.setRows(5);
        jScrollPane3.setViewportView(streetAdsField);

        postalCode.setText("Postal Code: ");

        city.setText("City: ");

        prov.setText("Prov: ");

        provCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BC", "Alberta", "Saskatchewan", "Manitoba", "Ontario", "Quebec", "Newbrunswick", "PEI", "Nova Scotia", "NL", "" }));

        phoneWork.setText("Phone_Work:");

        phoneHome.setText("phone_home:");

        try {
            phoneWorkField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("306-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            phoneHomeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("306-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout personPortionLayout = new javax.swing.GroupLayout(personPortion);
        personPortion.setLayout(personPortionLayout);
        personPortionLayout.setHorizontalGroup(
            personPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personPortionLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(personPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(personPortionLayout.createSequentialGroup()
                            .addComponent(streetAds)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane3))
                        .addGroup(personPortionLayout.createSequentialGroup()
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(personPortionLayout.createSequentialGroup()
                        .addGroup(personPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(personPortionLayout.createSequentialGroup()
                                .addComponent(phoneWork)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phoneWorkField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phoneHome)
                                .addGap(18, 18, 18)
                                .addComponent(phoneHomeField))
                            .addGroup(personPortionLayout.createSequentialGroup()
                                .addComponent(postalCode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(postalCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(prov, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(provCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        personPortionLayout.setVerticalGroup(
            personPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personPortionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(personPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(streetAds)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(personPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postalCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prov, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(provCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneWork)
                    .addComponent(phoneHome)
                    .addComponent(phoneWorkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneHomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        buttonPortion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        updateBtn.setText("update");
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
        });

        deleteBtn.setText("delete");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });

        saveBtn.setText("save");
        saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBtnMouseClicked(evt);
            }
        });

        loadBtn.setText("load");
        loadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadBtnMouseClicked(evt);
            }
        });

        createPersonBtn.setText("createPerson");
        createPersonBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createPersonBtnMouseClicked(evt);
            }
        });

        readBtn.setText("read");
        readBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readBtnMouseClicked(evt);
            }
        });

        exitButton.setText("exit");
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });

        createUnderBtn.setText("createUnStu");
        createUnderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createUnderBtnMouseClicked(evt);
            }
        });

        createGraBtn.setText("createGrastu");
        createGraBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createGraBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout buttonPortionLayout = new javax.swing.GroupLayout(buttonPortion);
        buttonPortion.setLayout(buttonPortionLayout);
        buttonPortionLayout.setHorizontalGroup(
            buttonPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPortionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createPersonBtn)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(buttonPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonPortionLayout.createSequentialGroup()
                        .addComponent(readBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPortionLayout.createSequentialGroup()
                        .addGroup(buttonPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createUnderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(buttonPortionLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(buttonPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(buttonPortionLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(createGraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(buttonPortionLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(loadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        buttonPortionLayout.setVerticalGroup(
            buttonPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPortionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(buttonPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createPersonBtn)
                    .addComponent(createUnderBtn)
                    .addComponent(createGraBtn))
                .addGap(18, 18, 18)
                .addGroup(buttonPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn)
                    .addComponent(updateBtn)
                    .addComponent(readBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(buttonPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveBtn)
                    .addGroup(buttonPortionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(loadBtn)
                        .addComponent(exitButton)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        underGradList.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.green, null));
        underGradList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                underGradListFocusGained(evt);
            }
        });
        underGradList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                underGradListMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(underGradList);

        gradList.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, null));
        gradList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gradListFocusGained(evt);
            }
        });
        gradList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradListMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(gradList);

        errorMsg.setBackground(new java.awt.Color(255, 255, 51));
        errorMsg.setForeground(new java.awt.Color(255, 51, 51));

        checkGra.setSelected(true);
        checkGra.setText("enableGraduation");
        checkGra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGraActionPerformed(evt);
            }
        });

        checkUngrad.setSelected(true);
        checkUngrad.setText("enableUnderGraduate");
        checkUngrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkUngradActionPerformed(evt);
            }
        });

        checkPerson.setSelected(true);
        checkPerson.setText("enablePerson");
        checkPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPersonActionPerformed(evt);
            }
        });

        resetPerson.setText("resetPerson");
        resetPerson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetPersonMouseClicked(evt);
            }
        });

        resetUngrad.setText("resetUngradua");
        resetUngrad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetUngradMouseClicked(evt);
            }
        });

        resetGrad.setText("resetGrad");
        resetGrad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetGradMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonPortion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkUngrad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetUngrad))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(undergraduatePortion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(personPortion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkPerson)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resetPerson)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(graduatePortion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkGra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resetGrad)))))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkGra)
                    .addComponent(resetGrad))
                .addGap(18, 18, 18)
                .addComponent(graduatePortion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkPerson)
                    .addComponent(resetPerson))
                .addGap(1, 1, 1)
                .addComponent(personPortion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkUngrad)
                    .addComponent(resetUngrad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(undergraduatePortion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(buttonPortion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(errorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createPersonBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createPersonBtnMouseClicked
        EmailValidator emailValidator = new EmailValidator();

        if (!emailValidator.validate(emailField.getText().trim())) {
            this.errorMsg.setText("Please enter a valid email"); 
        }
        else{
            this.errorMsg.setText("");
            pC.CreatePerson(nameField.getText(),new Address(streetAdsField.getText(),cityField.getText(),(String)provCombo.getSelectedItem(),postalCodeField.getText()),phoneHomeField.getText(),phoneWorkField.getText(),emailField.getText());   
        }
    }//GEN-LAST:event_createPersonBtnMouseClicked

    private void createUnderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createUnderBtnMouseClicked
        EmailValidator emailValidator = new EmailValidator();

        if (!emailValidator.validate(emailField.getText().trim())) {
            this.errorMsg.setText("Please enter a valid email"); 
        }
        else{
            this.errorMsg.setText("");
            pC.CreateUnderStudent( Integer.parseInt(regisYearField.getText()),(String)programCombo.getSelectedItem(),Integer.parseInt((String)programYearCombo.getSelectedItem()), Float.parseFloat(GPAField.getText()),Integer.parseInt(creditsField.getText()),nameField.getText(),new Address(streetAdsField.getText(),cityField.getText(),(String)provCombo.getSelectedItem(),postalCodeField.getText()),phoneHomeField.getText(),phoneWorkField.getText(),emailField.getText());            
        }    
        
    }//GEN-LAST:event_createUnderBtnMouseClicked

    private void createGraBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createGraBtnMouseClicked
        // TODO add your handling code here:
        
       EmailValidator emailValidator = new EmailValidator();

        if (!emailValidator.validate(emailField.getText().trim()) || !emailValidator.validate(emailField_prof.getText().trim())) {
            this.errorMsg.setText("Please enter a valid email"); 
        }
        else{
            this.errorMsg.setText("");
            pC.CreateGradStudent(new person(nameField_prof.getText(),new Address(streetAdsField_prof.getText(),cityField_prof.getText(),(String)provCombo_prof.getSelectedItem(),postalCodeField_prof.getText()),phoneHomeField_prof.getText(),phoneWorkField_prof.getText(),emailField_prof.getText()),new Thesis(titleField.getText(),areaField.getText()),Integer.parseInt(scholarshipField.getText()),(String)degreeCombo.getSelectedItem(),Integer.parseInt(regisYearField.getText()),(String)programCombo.getSelectedItem(),Integer.parseInt((String)programYearCombo.getSelectedItem()), Float.parseFloat(GPAField.getText()),Integer.parseInt(creditsField.getText()),nameField.getText(),new Address(streetAdsField.getText(),cityField.getText(),(String)provCombo.getSelectedItem(),postalCodeField.getText()),phoneHomeField.getText(),phoneWorkField.getText(),emailField.getText());            
        }
    }//GEN-LAST:event_createGraBtnMouseClicked

    private void saveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseClicked
        try {
            // TODO add your handling code here:
            pC.writeToFile();
        } catch (IOException ex) {
            Logger.getLogger(person_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveBtnMouseClicked

    private void loadBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadBtnMouseClicked
        try {
            // TODO add your handling code here:
            pC.readFromFile();
        } catch (IOException ex) {
            Logger.getLogger(person_Interface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(person_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        personList.repaint();
        underGradList.repaint();
        gradList.repaint();
    }//GEN-LAST:event_loadBtnMouseClicked

    private void readBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readBtnMouseClicked
        // TODO add your handling code here:
        
        if(!personList.isSelectionEmpty()){
            
            this.setPanelEnabled(this.personPortion, true);
            this.setPanelEnabled(this.undergraduatePortion, false);
            this.setPanelEnabled(this.graduatePortion, false);
            person temp = personList.getSelectedValue();
            nameField.setText(temp.Name);
            streetAdsField.setText(temp.address.street);
            postalCodeField.setText(temp.address.postal_code);
            cityField.setText(temp.address.city);
            provCombo.setSelectedItem(temp.address.prov);
            emailField.setText(temp.Email);
            phoneWorkField.setText(temp.PhonenumHome);
            phoneHomeField.setText(temp.PhonenumWork);            
        }
        
        if(!underGradList.isSelectionEmpty()){
            
            this.setPanelEnabled(this.personPortion, true);
            this.setPanelEnabled(this.undergraduatePortion, true);
            this.setPanelEnabled(this.graduatePortion, false);
            UndergradStudent temp = underGradList.getSelectedValue();
            nameField.setText(temp.Name);
            streetAdsField.setText(temp.address.street);
            postalCodeField.setText(temp.address.postal_code);
            cityField.setText(temp.address.city);
            provCombo.setSelectedItem(temp.address.prov);
            emailField.setText(temp.Email);
            phoneWorkField.setText(temp.PhonenumHome);
            phoneHomeField.setText(temp.PhonenumWork); 
            
            regisYearField.setText(Integer.toString(temp.YearRegistered));
            programCombo.setSelectedItem(temp.DegreeProgram);
            programYearCombo.setSelectedItem(Integer.toString(temp.YearInProgram));
            GPAField.setText(Float.toString(temp.GPA));
            creditsField.setText(Integer.toString(temp.TotalCredits)); 
            
           
        }
        
        if(!gradList.isSelectionEmpty()){
            this.setPanelEnabled(this.personPortion, true);
            this.setPanelEnabled(this.undergraduatePortion, true);
            this.setPanelEnabled(this.graduatePortion, true);
            GraduateStudent temp = gradList.getSelectedValue();
            nameField.setText(temp.Name);
            streetAdsField.setText(temp.address.street);
            postalCodeField.setText(temp.address.postal_code);
            cityField.setText(temp.address.city);
            provCombo.setSelectedItem(temp.address.prov);
            emailField.setText(temp.Email);
            phoneWorkField.setText(temp.PhonenumHome);
            phoneHomeField.setText(temp.PhonenumWork); 
            
            regisYearField.setText(Integer.toString(temp.YearRegistered));
            programCombo.setSelectedItem(temp.DegreeProgram);
            programYearCombo.setSelectedItem(Integer.toString(temp.YearInProgram));
            GPAField.setText(Float.toString(temp.GPA));
            creditsField.setText(Integer.toString(temp.TotalCredits));  
            
            scholarshipField.setText(Integer.toString(temp.ScholarShipAmount));
            degreeCombo.setSelectedItem(temp.degreeType);
            nameField_prof.setText(temp.ThesisSupervior.Name);
            streetAdsField_prof.setText(temp.ThesisSupervior.address.street);
            postalCodeField_prof.setText(temp.ThesisSupervior.address.postal_code);
            cityField_prof.setText(temp.ThesisSupervior.address.city);
            provCombo_prof.setSelectedItem(temp.ThesisSupervior.address.prov);
            emailField_prof.setText(temp.ThesisSupervior.Email);
            phoneWorkField_prof.setText(temp.ThesisSupervior.PhonenumHome);
            phoneHomeField_prof.setText(temp.ThesisSupervior.PhonenumWork); 
            titleField.setText(temp.myThesis.title);
            areaField.setText(temp.myThesis.area);
            
        }
        
       
    }//GEN-LAST:event_readBtnMouseClicked

    private void personListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_personListFocusGained
        // TODO add your handling code here:
        underGradList.clearSelection();
        gradList.clearSelection();
        checkPerson.setSelected(true);
        checkUngrad.setSelected(false);
        checkGra.setSelected(false);

    }//GEN-LAST:event_personListFocusGained

    private void underGradListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_underGradListFocusGained
        // TODO add your handling code here:
        personList.clearSelection();
        gradList.clearSelection();
        checkPerson.setSelected(true);
        checkUngrad.setSelected(true);
        checkGra.setSelected(false);
    }//GEN-LAST:event_underGradListFocusGained

    private void gradListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gradListFocusGained
        // TODO add your handling code here:
        underGradList.clearSelection();
        personList.clearSelection();
        checkPerson.setSelected(true);
        checkUngrad.setSelected(true);
        checkGra.setSelected(true);
    }//GEN-LAST:event_gradListFocusGained

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        // TODO add your handling code here:
        int index,flag;
        if(!personList.isSelectionEmpty()){
            index = personList.getSelectedIndex();
            flag = 1;
            pC.delete(index,flag);
        }
        
        if(!underGradList.isSelectionEmpty()){
            index = underGradList.getSelectedIndex();
            flag = 2;
            pC.delete(index,flag);
        }
        
        if(!gradList.isSelectionEmpty()){
            index =gradList.getSelectedIndex();
            flag = 3;
            pC.delete(index,flag);
        }
        
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitButtonMouseClicked

    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked
        // TODO add your handling code here:
        
        if (!personList.isSelectionEmpty()) {
            int index = personList.getSelectedIndex();
            pC.UpdatePerson(nameField.getText(),new Address(streetAdsField.getText(),cityField.getText(),(String)provCombo.getSelectedItem(),postalCodeField.getText()),phoneHomeField.getText(),phoneWorkField.getText(),emailField.getText(), index);           

        }

        if (!underGradList.isSelectionEmpty()) {
            int index = underGradList.getSelectedIndex();
            pC.UpdateUndergraStu( Integer.parseInt(regisYearField.getText()),(String)programCombo.getSelectedItem(),Integer.parseInt((String)programYearCombo.getSelectedItem()), Float.parseFloat(GPAField.getText()),Integer.parseInt(creditsField.getText()),nameField.getText(),new Address(streetAdsField.getText(),cityField.getText(),(String)provCombo.getSelectedItem(),postalCodeField.getText()),phoneHomeField.getText(),phoneWorkField.getText(),emailField.getText(), index);  

        }

        if (!gradList.isSelectionEmpty()) {
            int index = gradList.getSelectedIndex();
            pC.UpdateGradStu(new person(nameField_prof.getText(),new Address(streetAdsField_prof.getText(),cityField_prof.getText(),(String)provCombo_prof.getSelectedItem(),postalCodeField_prof.getText()),phoneHomeField_prof.getText(),phoneWorkField_prof.getText(),emailField_prof.getText()),new Thesis(titleField.getText(),areaField.getText()),Integer.parseInt(scholarshipField.getText()),(String)degreeCombo.getSelectedItem(),Integer.parseInt(regisYearField.getText()),(String)programCombo.getSelectedItem(),Integer.parseInt((String)programYearCombo.getSelectedItem()), Float.parseFloat(GPAField.getText()),Integer.parseInt(creditsField.getText()),nameField.getText(),new Address(streetAdsField.getText(),cityField.getText(),(String)provCombo.getSelectedItem(),postalCodeField.getText()),phoneHomeField.getText(),phoneWorkField.getText(),emailField.getText(), index);            

        }
    }//GEN-LAST:event_updateBtnMouseClicked

    private void personListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personListMouseClicked
        // TODO add your handling code here:
            this.setPanelEnabled(this.personPortion, true);
            this.setPanelEnabled(this.undergraduatePortion, false);
            this.setPanelEnabled(this.graduatePortion, false);
            person temp = personList.getSelectedValue();
            nameField.setText(temp.Name);
            streetAdsField.setText(temp.address.street);
            postalCodeField.setText(temp.address.postal_code);
            cityField.setText(temp.address.city);
            provCombo.setSelectedItem(temp.address.prov);
            emailField.setText(temp.Email);
            phoneWorkField.setText(temp.PhonenumHome);
            phoneHomeField.setText(temp.PhonenumWork); 
           
        
    }//GEN-LAST:event_personListMouseClicked

    private void underGradListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_underGradListMouseClicked
            
            this.setPanelEnabled(this.personPortion, true);
            this.setPanelEnabled(this.undergraduatePortion, true);
            this.setPanelEnabled(this.graduatePortion, false);
            UndergradStudent temp = underGradList.getSelectedValue();
            nameField.setText(temp.Name);
            streetAdsField.setText(temp.address.street);
            postalCodeField.setText(temp.address.postal_code);
            cityField.setText(temp.address.city);
            provCombo.setSelectedItem(temp.address.prov);
            emailField.setText(temp.Email);
            phoneWorkField.setText(temp.PhonenumHome);
            phoneHomeField.setText(temp.PhonenumWork); 
            
            regisYearField.setText(Integer.toString(temp.YearRegistered));
            programCombo.setSelectedItem(temp.DegreeProgram);
            programYearCombo.setSelectedItem(Integer.toString(temp.YearInProgram));
            GPAField.setText(Float.toString(temp.GPA));
            creditsField.setText(Integer.toString(temp.TotalCredits)); 
            
            
    }//GEN-LAST:event_underGradListMouseClicked

    private void gradListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradListMouseClicked
         
            this.setPanelEnabled(this.personPortion, true);
            this.setPanelEnabled(this.undergraduatePortion, true);
            this.setPanelEnabled(this.graduatePortion, true);
            GraduateStudent temp = gradList.getSelectedValue();
            nameField.setText(temp.Name);
            streetAdsField.setText(temp.address.street);
            postalCodeField.setText(temp.address.postal_code);
            cityField.setText(temp.address.city);
            provCombo.setSelectedItem(temp.address.prov);
            emailField.setText(temp.Email);
            phoneWorkField.setText(temp.PhonenumHome);
            phoneHomeField.setText(temp.PhonenumWork); 
            
            regisYearField.setText(Integer.toString(temp.YearRegistered));
            programCombo.setSelectedItem(temp.DegreeProgram);
            programYearCombo.setSelectedItem(Integer.toString(temp.YearInProgram));
            GPAField.setText(Float.toString(temp.GPA));
            creditsField.setText(Integer.toString(temp.TotalCredits));  
            
            scholarshipField.setText(Integer.toString(temp.ScholarShipAmount));
            degreeCombo.setSelectedItem(temp.degreeType);
            nameField_prof.setText(temp.ThesisSupervior.Name);
            streetAdsField_prof.setText(temp.ThesisSupervior.address.street);
            postalCodeField_prof.setText(temp.ThesisSupervior.address.postal_code);
            cityField_prof.setText(temp.ThesisSupervior.address.city);
            provCombo_prof.setSelectedItem(temp.ThesisSupervior.address.prov);
            emailField_prof.setText(temp.ThesisSupervior.Email);
            phoneWorkField_prof.setText(temp.ThesisSupervior.PhonenumHome);
            phoneHomeField_prof.setText(temp.ThesisSupervior.PhonenumWork); 
            titleField.setText(temp.myThesis.title);
            areaField.setText(temp.myThesis.area);
            
           
    }//GEN-LAST:event_gradListMouseClicked

    private void checkGraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGraActionPerformed
        
        if(checkGra.isSelected()){
            this.setPanelEnabled(this.graduatePortion, true);           
        }
        else
            this.setPanelEnabled(this.graduatePortion, false);
    }//GEN-LAST:event_checkGraActionPerformed

    private void checkUngradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkUngradActionPerformed

        if(checkUngrad.isSelected()){
            this.setPanelEnabled(this.undergraduatePortion, true);           
        }
        else
            this.setPanelEnabled(this.undergraduatePortion, false);
    }//GEN-LAST:event_checkUngradActionPerformed

    private void checkPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPersonActionPerformed
        
        if(checkPerson.isSelected()){
            this.setPanelEnabled(this.personPortion, true);          
        }
        else
            this.setPanelEnabled(this.personPortion, false);
    }//GEN-LAST:event_checkPersonActionPerformed

    private void resetPersonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPersonMouseClicked
        // TODO add your handling code here:
            nameField.setText("");
            streetAdsField.setText("");
            postalCodeField.setText("");
            cityField.setText("");
            emailField.setText("");
            phoneWorkField.setText("");
            phoneHomeField.setText("");        
    }//GEN-LAST:event_resetPersonMouseClicked

    private void resetUngradMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetUngradMouseClicked
            regisYearField.setText("");
            GPAField.setText("");
            creditsField.setText(""); 
    }//GEN-LAST:event_resetUngradMouseClicked

    private void resetGradMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetGradMouseClicked
            scholarshipField.setText("");
            nameField_prof.setText("");
            streetAdsField_prof.setText("");
            postalCodeField_prof.setText("");
            cityField_prof.setText("");
            emailField_prof.setText("");
            phoneWorkField_prof.setText("");
            phoneHomeField_prof.setText(""); 
            titleField.setText("");
            areaField.setText(""); 
    }//GEN-LAST:event_resetGradMouseClicked

    public class EmailValidator {

        private Pattern pattern;
        private Matcher matcher;

        private static final String EMAIL_PATTERN
                = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

        public EmailValidator() {
            pattern = Pattern.compile(EMAIL_PATTERN);
        }

        /**
         * Validate hex with regular expression
         *
         * @param hex hex for validation
         * @return true valid hex, false invalid hex
         */
        public boolean validate(final String hex) {

            matcher = pattern.matcher(hex);
            return matcher.matches();

        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(person_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(person_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(person_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(person_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Thread t1 = new Thread(new Runnable(){
                    @Override
                    public void run(){
                        new person_Interface().setVisible(true);
                    }
                });
                Thread t2 = new Thread(new Runnable(){
                    @Override
                    public void run(){
                        new person_Interface().setVisible(true);
                    }
                });
                
                t1.start();
              
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) {
                    Logger.getLogger(person_Interface.class.getName()).log(Level.SEVERE, null, ex);
                }
               
                t2.start();
                //new Zoo().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DegreeType;
    private javax.swing.JLabel GPA;
    private javax.swing.JTextField GPAField;
    private javax.swing.JLabel area;
    private javax.swing.JTextArea areaField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel buttonPortion;
    private javax.swing.JCheckBox checkGra;
    private javax.swing.JCheckBox checkPerson;
    private javax.swing.JCheckBox checkUngrad;
    private javax.swing.JLabel city;
    private javax.swing.JTextField cityField;
    private javax.swing.JTextField cityField_prof;
    private javax.swing.JLabel city_prof;
    private javax.swing.JButton createGraBtn;
    private javax.swing.JButton createPersonBtn;
    private javax.swing.JButton createUnderBtn;
    private javax.swing.JLabel credits;
    private javax.swing.JTextField creditsField;
    private javax.swing.JComboBox<String> degreeCombo;
    private javax.swing.JLabel degreeProgram;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField emailField_prof;
    private javax.swing.JLabel email_prof;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JButton exitButton;
    protected javax.swing.JList<GraduateStudent> gradList;
    private javax.swing.JPanel graduatePortion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loadBtn;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nameField_prof;
    private javax.swing.JLabel name_prof;
    protected javax.swing.JList<person> personList;
    private javax.swing.JPanel personPortion;
    private javax.swing.JPanel personPortion1;
    private javax.swing.JLabel phoneHome;
    private javax.swing.JFormattedTextField phoneHomeField;
    private javax.swing.JFormattedTextField phoneHomeField_prof;
    private javax.swing.JLabel phoneHome_prof;
    private javax.swing.JLabel phoneWork;
    private javax.swing.JFormattedTextField phoneWorkField;
    private javax.swing.JFormattedTextField phoneWorkField_prof;
    private javax.swing.JLabel phoneWork_prof;
    private javax.swing.JLabel postalCode;
    private javax.swing.JTextField postalCodeField;
    private javax.swing.JTextField postalCodeField_prof;
    private javax.swing.JLabel postalCode_prof;
    private javax.swing.JComboBox<String> programCombo;
    private javax.swing.JLabel programYear;
    private javax.swing.JComboBox<String> programYearCombo;
    private javax.swing.JLabel prov;
    private javax.swing.JComboBox<String> provCombo;
    private javax.swing.JComboBox<String> provCombo_prof;
    private javax.swing.JLabel prov_prof;
    private javax.swing.JButton readBtn;
    private javax.swing.JTextField regisYearField;
    private javax.swing.JLabel registerYear;
    private javax.swing.JButton resetGrad;
    private javax.swing.JButton resetPerson;
    private javax.swing.JButton resetUngrad;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel scholarship;
    private javax.swing.JTextField scholarshipField;
    private javax.swing.JLabel streetAds;
    private javax.swing.JTextArea streetAdsField;
    private javax.swing.JTextArea streetAdsField_prof;
    private javax.swing.JLabel streetAds_prof;
    private javax.swing.JPanel supervisorPortion;
    private javax.swing.JLabel supervisorTitle;
    private javax.swing.JPanel thesisPortion;
    private javax.swing.JLabel title;
    private javax.swing.JTextArea titleField;
    protected javax.swing.JList<UndergradStudent> underGradList;
    private javax.swing.JPanel undergraduatePortion;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
